#!/bin/sh
#
# Copyright (C) 2016 Glenn 'devalias' Grant (devalias.net)
#
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.
#

# TODO: Roll all the mongo scripts into a single file (python?)
# TODO: Make this accept a 'project name' and use seperate databases for each

# echo "This won't work because fsync issue with virtualbox and shared directories in virtualbox: https://docs.mongodb.org/manual/administration/production-notes/#fsync-on-directories"
# exit 1

#run -d -P --name lair-mongo -v /src/webapp:/opt/webapp training/webapp python app.py
LAIR_PATH="$HOME/sec/lair"
LAIR_DB_PATH="$LAIR_PATH/data/db/"
CONTAINER_NAME="ezlair-mongo"
EZHEAD="[ezLair-mongo-create]"

echo "$EZHEAD Creating DB path: $LAIR_DB_PATH"
cd "$LAIR_PATH"
mkdir -p "$LAIR_DB_PATH"

echo "$EZHEAD Running docker container: $CONTAINER_NAME"
docker run -d -p 127.0.0.1:27017:27017 -v $LAIR_DB_PATH:/data/db --name $CONTAINER_NAME mongo --replSet rs0

docker ps -a -f name=$CONTAINER_NAME

echo "$EZHEAD Sleeping 2s for mongo startup.."
sleep 2s

echo "$EZHEAD Configuring replica set.."
REPSET_CMD='rs.initiate({_id:"rs0", members: [{_id: 1, host: "localhost:27017"}]})'
docker exec "$CONTAINER_NAME" mongo admin --eval "$REPSET_CMD"
echo
if [ "$?" == "0" ]; then
  echo "$EZHEAD Replica set configured."
else
  echo "$EZHEAD Error: Configuring replica set failed. You'll need to run the following command yourself:"
  echo "  docker exec $CONTAINER_NAME mongo admin --eval '$REPSET_CMD'"
fi

echo "$EZHEAD All done. Enjoy!"
