#!/bin/sh
#
# Copyright (C) 2016 Glenn 'devalias' Grant (devalias.net)
#
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.
#
cd "$HOME/sec/lair/"

EZHEAD="[ezLair-api-start]"

echo "$EZHEAD Starting API.."

# Lair API Env Vars
export MONGO_URL=mongodb://localhost:27017/lair
export API_LISTENER=localhost:11015

API_VER=`cat api-version`

eval "./api-server_darwin_amd64-$API_VER"
