#!/bin/sh
#
# Copyright (C) 2016 Glenn 'devalias' Grant (devalias.net)
#
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.
#

EZHEAD="[ezLair-cleanup]"

echo "$EZHEAD Cleaning up all data.."
./ezlair-mongo-reset

echo "$EZHEAD Removing created files/directories.."
rm -rf ./data ./files ./bundle
rm -f ./api-server_*
rm -f ./lair-v*.tar.gz
rm -f ./app-version
rm -f ./api-version

echo "$EZHEAD All clean!"